### ISSUE TITLE
Please cite our paper

### ISSUE THREAD

**Issue by sirbastiano** [pbeukema/wakemodel_llmassist#3]
We are happy that our dataset and paper has shown interest in the CV community. This library is by far the most similar implementation from our paper: https://ieeexplore.ieee.org/document/10285362
Also the dataset come from the paper mentioned before.

**Comment by pbeukema** [comment]
Thank you for the note and please accept my apologies for the oversight (the blog post did reference your work). I have updated the readme (https://github.com/pbeukema/wakemodel_llmassist/commit/3d9cc215082c1033589c26f8f535fad6183ba7e2) with this citation/acknowledgement but please let me know if you would like me to do anything further/or modify the citation.  

Sincere thanks for doing this work and publicly releasing your dataset under a permissive license.

**Comment by sirbastiano** [comment]
I kindly thank you again for using our work! Thanks!
